/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MonthsRouteImport } from './routes/months'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MonthsIndexRouteImport } from './routes/months.index'
import { Route as MonthsMonthIdRouteImport } from './routes/months.$monthId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthsRoute = MonthsRouteImport.update({
  id: '/months',
  path: '/months',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthsIndexRoute = MonthsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MonthsRoute,
} as any)
const MonthsMonthIdRoute = MonthsMonthIdRouteImport.update({
  id: '/$monthId',
  path: '/$monthId',
  getParentRoute: () => MonthsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/months': typeof MonthsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/months/$monthId': typeof MonthsMonthIdRoute
  '/months/': typeof MonthsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/months/$monthId': typeof MonthsMonthIdRoute
  '/months': typeof MonthsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/months': typeof MonthsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/months/$monthId': typeof MonthsMonthIdRoute
  '/months/': typeof MonthsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ledger'
    | '/login'
    | '/members'
    | '/months'
    | '/profile'
    | '/reports'
    | '/months/$monthId'
    | '/months/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ledger'
    | '/login'
    | '/members'
    | '/profile'
    | '/reports'
    | '/months/$monthId'
    | '/months'
  id:
    | '__root__'
    | '/'
    | '/ledger'
    | '/login'
    | '/members'
    | '/months'
    | '/profile'
    | '/reports'
    | '/months/$monthId'
    | '/months/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LedgerRoute: typeof LedgerRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  MonthsRoute: typeof MonthsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/months': {
      id: '/months'
      path: '/months'
      fullPath: '/months'
      preLoaderRoute: typeof MonthsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/months/': {
      id: '/months/'
      path: '/'
      fullPath: '/months/'
      preLoaderRoute: typeof MonthsIndexRouteImport
      parentRoute: typeof MonthsRoute
    }
    '/months/$monthId': {
      id: '/months/$monthId'
      path: '/$monthId'
      fullPath: '/months/$monthId'
      preLoaderRoute: typeof MonthsMonthIdRouteImport
      parentRoute: typeof MonthsRoute
    }
  }
}

interface MonthsRouteChildren {
  MonthsMonthIdRoute: typeof MonthsMonthIdRoute
  MonthsIndexRoute: typeof MonthsIndexRoute
}

const MonthsRouteChildren: MonthsRouteChildren = {
  MonthsMonthIdRoute: MonthsMonthIdRoute,
  MonthsIndexRoute: MonthsIndexRoute,
}

const MonthsRouteWithChildren =
  MonthsRoute._addFileChildren(MonthsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LedgerRoute: LedgerRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  MonthsRoute: MonthsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
